const NOT_FOUND_ERROR = 404;
const BAD_REQUEST_ERROR = 400;
const INTERNAL_ERROR = 500;
const BAD_GATEWAY = 502;
const RESPONSE_OK = 200;
const RESPONSE_OK_CREATED = 201;
const RESPONSE_OK_UPDATED = 201;
const RESPONSE_OK_NO_CONTENT = 204;
const REQUEST_TIMEOUT = 408;
const NOK_USER_CREDENTIALS = 401;
const FORBIDDEN = 403;
const SECRETORPRIVATEKEY = 'SECRETKEY';


module.exports = {
  NOT_FOUND_ERROR,
  BAD_REQUEST_ERROR,
  INTERNAL_ERROR,
  BAD_GATEWAY,
  RESPONSE_OK,
  RESPONSE_OK_CREATED,
  RESPONSE_OK_UPDATED,
  RESPONSE_OK_NO_CONTENT,
  REQUEST_TIMEOUT,
  NOK_USER_CREDENTIALS,
  FORBIDDEN,
  SECRETORPRIVATEKEY,
};
